name: GTest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone GTest
      run:  git clone https://github.com/google/googletest.git -b release-1.10.0
    - name: Install gtest manually
      working-directory: ./pz3
      run:  sudo apt install python3-pip &&
            cmake . &&
            make &&
            sudo make install
    - uses: actions/checkout@v1
    - name: make
      run: make

